"""
==========================================================
Smart Insole DFU Risk Prediction
Backend Utilities

Contains common helper functions, standardized JSON 
responses, custom JSON encoders, and logging configuration.
==========================================================
"""

import logging
import json
import numpy as np
from datetime import datetime
from typing import Any, Dict, Optional, Tuple, List, Iterable

# ==========================================================
# 1. Logging Configuration
# ==========================================================
def setup_professional_logging(app_name: str = "DFU_Backend") -> logging.Logger:
    """
    Configures and returns a professional logger with standardized formatting.
    Prevents duplicate handlers if called multiple times.
    """
    logger = logging.getLogger(app_name)
    logger.propagate = False
    
    # Only configure if it hasn't been configured yet
    if not logger.handlers:
        logger.setLevel(logging.INFO)
        
        console_handler = logging.StreamHandler()
        console_handler.setLevel(logging.INFO)
        
        # Professional standard timestamped format
        formatter = logging.Formatter(
            '%(asctime)s | %(name)s | %(levelname)s | %(message)s',
            datefmt='%Y-%m-%d %H:%M:%S'
        )
        
        console_handler.setFormatter(formatter)
        logger.addHandler(console_handler)
        
    return logger


# ==========================================================
# 2. Standardized API Responses
# ==========================================================
def format_success(
    data: Any, 
    message: str = "Success", 
    status_code: int = 200, 
    include_timestamp: bool = False
) -> Tuple[Dict[str, Any], int]:
    """
    Wraps API success output in a standardized envelope.
    
    Returns
    -------
    Tuple[dict, int]
        Flask-compatible JSON dictionary and HTTP status code.
    """
    response: Dict[str, Any] = {
        "status": "success",
        "message": message
    }
    
    if include_timestamp:
        response["timestamp"] = datetime.now().isoformat()
        
    response["data"] = data
    
    return response, status_code

def format_error(
    message: str, 
    error_code: int = 400, 
    details: Optional[Any] = None,
    error_type: Optional[str] = None,
    include_timestamp: bool = False
) -> Tuple[Dict[str, Any], int]:
    """
    Wraps API errors in a standardized envelope.
    
    Returns
    -------
    Tuple[dict, int]
        Flask-compatible JSON dictionary and HTTP error status code.
    """
    response: Dict[str, Any] = {
        "status": "error",
        "message": message
    }
    
    if error_type:
        response["error_type"] = error_type
        
    if include_timestamp:
        response["timestamp"] = datetime.now().isoformat()
        
    if details:
        response["details"] = details
        
    return response, error_code


# ==========================================================
# 3. Custom JSON Encoders
# ==========================================================
class NumpyEncoder(json.JSONEncoder):
    """
    Custom JSON encoder to seamlessly handle NumPy data types.
    Ensures the Flask backend won't crash with TypeError when returning
    data generated by pandas, numpy, or tensorflow models.
    """
    def default(self, obj: Any) -> Any:
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        elif isinstance(obj, np.bool_):
            return bool(obj)
        elif isinstance(obj, np.generic):
            return obj.item()
        return super().default(obj)


# ==========================================================
# 4. Dictionary Validation Helpers
# ==========================================================
def get_missing_keys(payload: Dict[str, Any], required_keys: Iterable[str]) -> List[str]:
    """
    Validates that a dictionary contains all required keys.
    
    Returns
    -------
    list
        A list of missing string keys. Empty if all are present.
    """
    if not isinstance(required_keys, (list, set, tuple)):
        raise TypeError("required_keys must be an iterable (e.g., list or tuple).")
        
    if not isinstance(payload, dict):
        return list(required_keys)
        
    return [key for key in required_keys if key not in payload]

def validate_required_keys(payload: Dict[str, Any], required_keys: Iterable[str]) -> None:
    """
    Validates that a dictionary contains all required keys.
    Raises a ValueError if any keys are missing.
    
    Parameters
    ----------
    payload : dict
        The dictionary to validate.
    required_keys : iterable
        A list of expected string keys.
        
    Raises
    ------
    ValueError
        If any required keys are missing.
    """
    missing_keys = get_missing_keys(payload, required_keys)
    if missing_keys:
        raise ValueError(f"Missing required keys: {', '.join(missing_keys)}")
    return None
